name = "add-plex-request"
main = "src/worker.ts"
compatibility_date = "2023-10-10"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[vars]
NOTION_PLEX_REQUEST_DATABASE_ID = "e5296ba6f21845cf85201c96e50bddb9"
SENDGRID_FROM_EMAIL = "nikitabot@gamolsky.net"
SENDGRID_TO_EMAIL = "plexrequest@gamolsky.net"

routes = [
	{ pattern = "api.gamolsky.net", custom_domain = true },
]
